apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: synchub-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: IMAGE_PLACEHOLDER
          ports:
            - name: http1
              containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
            - name: CORS_ORIGIN
              value: https://synchhub.com,http://localhost:3000
            - name: SUPABASE_URL
              value: https://ds.synchhub.com
            - name: TIKTOK_REDIRECT_URI
              value: https://api.synchhub.com/api/v1/social-accounts/callback/tiktok
            - name: FRONTEND_URL
              value: https://synchhub.com
            - name: FB_REDIRECT_URI
              value: https://api.synchhub.com/api/v1/social-accounts/callback/facebook
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  key: '2'
                  name: synchub-api-supabase-anon-key
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  key: '2'
                  name: synchub-api-supabase-service-role-key
            - name: AUTH_HASH_SECRET
              valueFrom:
                secretKeyRef:
                  key: '1'
                  name: synchub-api-auth-hash-secret
            - name: TOKEN_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  key: '1'
                  name: synchub-api-token-encryption-key
            - name: TIKTOK_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  key: '2'
                  name: synchub-api-tiktok-client-key
            - name: TIKTOK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: '2'
                  name: synchub-api-tiktok-client-secret
            - name: FB_APP_ID
              valueFrom:
                secretKeyRef:
                  key: '1'
                  name: synchub-api-fb-app-id
            - name: FB_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: '1'
                  name: synchub-api-fb-app-secret
          startupProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            periodSeconds: 30
            failureThreshold: 3
          resources:
            limits:
              cpu: '1'
              memory: 128Mi
